### ISSUE TITLE
missing "function1Local_modif" function

### ISSUE THREAD

**Issue by michells** [yolandalago/CIRCUST#1]
When I run the example code, I run into an error at #3.1. The error statement is:
Error in function1Local_modif(datos[i, ], parallel = "auto") : 
  could not find function "function1Local_modif"

**Comment by yolandalago** [comment]
Thanks for the comment. The code has been updated.

**Comment by michells** [comment]
Hi Yolanda, thank you for the quick update! I am having another issue with the "upDownUp_NP_Code_NoParalelizado" script. I am unable to dyn.load "pava.dll" and "busquedaMejor.dll" because the files do not exist?

**Comment by yolandalago** [comment]
Please try again.

**Comment by michells** [comment]
Thank you, it all works now. Just one more question- can you please advise on how I can output the circust estimates for the circadian phase time for each sample?

**Comment by yolandalago** [comment]
As the key output of interest in our paper is the FMM parameters, we did not explicitly provide the details in the text, but you can obtain them from the code. For functions such as 'basicOrder_cores,' which calculates the circular order, the phase estimates are the second element in the list provided as output, labeled as 'escNewNew.' In general, I use the terminology 'esc' to refer to these values in functions that involve circular order estimation.
