### ISSUE TITLE
Sample-level results

### ISSUE THREAD

**Issue by lvclark** [yolandalago/CIRCUST#3]
I just ran through the example code. Where in the results can I see the angle for each sample indicating its position in the circadian cycle? Is it `robEstRefG[[2]][[1]][[2]]`?

In general it would be very helpful if the functions and their inputs and outputs were documented. A lot of the functions return lists, and these lists could be given `names` to make it a little more obvious what each item is.  This is not only important from a user's perspective, but also a maintainer's, because maintaining the software is difficult if there isn't documentation!

**Comment by yolandalago** [comment]
Hi Ivclark, 
The angle for each sample indicates its position in the circadian is given as the matrix: robustSincroRefG[[6]]. Each row of this matrix corresponds to one of the repetitions considered. robEstRefG[[2]][[1]] contains these orders, but, in some occasions, they could be in the inverse order, as the synchronization done in the next step is needed (robustSincroRefG).
Thanks for your suggestions. I am working on an improvement code.

**Comment by lvclark** [comment]
Great, thank you!

**Comment by christosdominosnickholasjesus-ai** [comment]
Jun 10, Misɛl Lin Meri Jizɔs Kristos Dɔminiɔs Kɔpas christi
